CRUD da Cooperativa
conab-devs/conab-backend pull request #35
Opened 2020-09-01 13:00 UTC by lucasemanuel8

## Descrição :pencil:
Desenvolvimento do CRUD da cooperativa, junto das rotas para requisitar as operações e das factories.

**Issues :pushpin:**
#2 

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [x] Alteração no gitignore :see_no_evil:
- [ ] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:
 >Caso esse Pull Request seja relacionado com **frontend** é crucial ter alguma imagem para a revisão.

2020-09-01 14:19 UTC, hdev14 commented on app/Http/Controllers/Api/CooperativeController.php
> +        $cooperative->phones()->createMany($request->input('phones'));
Faltou o upload do dap.

2020-09-01 14:57 UTC, FrankKleiton commented on app/Http/Controllers/Api/CooperativeController.php
> +    public function store(Request $request)
Gostei, ficou muito clean.

2020-09-01 15:01 UTC, FrankKleiton commented on app/Http/Controllers/Api/CooperativeController.php
> +                Rule::unique('phones')->whereNotIn('id', $cooperative->phones->modelKeys()),
Massa

2020-09-01 15:03 UTC, FrankKleiton commented on app/Http/Controllers/Api/CooperativeController.php
> +        if (!empty($phones = $request->input('phones'))) {
Gostei

2020-09-01 18:30 UTC, hdev14 commented on routes/api.php
> +Route::put('cooperatives/{id}', 'Api\\CooperativeController@update');
Faltou o middleware de autenticação, mas como vc não está usando testes a gente pode adicionar o middleware depois, na branch de release.

2020-09-02 12:07 UTC, hdev14 commented on routes/api.php
> +Route::get('cooperatives', 'Api\\CooperativeController@index');
Vi agora que você colocou os controllers dentro de um diretório API. A gente poderia ter feito assim, mas nem eu nem frank fizemos desse jeito, pra manter o código "padronizado" seria melhor vc deixa na pasta normal mesmo.

2020-09-02 16:57 UTC, lucasemanuel8 commented on routes/api.php
> +Route::get('cooperatives', 'Api\\CooperativeController@index');
Beleza

2020-09-02 17:00 UTC, lucasemanuel8 commented on app/Http/Controllers/Api/CooperativeController.php
> +        $cooperative->phones()->createMany($request->input('phones'));
Agora ta executando o upload do DAP.

2020-09-02 17:00 UTC, lucasemanuel8 commented on routes/api.php
> +Route::get('cooperatives', 'Api\\CooperativeController@index');
Já move o controlador da cooperativa.

2020-09-02 17:00 UTC, lucasemanuel8 commented on routes/api.php
> +Route::put('cooperatives/{id}', 'Api\\CooperativeController@update');
Inseri no merge.

2020-09-03 00:38 UTC, hdev14 requested changes
@lucasemanuel8 na linha 62 do controller da cooperativa faltou retornar os dados da cooperativa, pq pode precisar para poder registrar os administradores depois.

2020-09-03 12:03 UTC, lucasemanuel8 reviewed
Retornando cooperativa após salvar.

2020-09-03 14:48 UTC, hdev14 approved these changes
:coffee:

2020-09-03 14:49 UTC, hdev14 commented
Resolva os conflitos e faça o merge, depois vamos fazer uma branch de release para poder verificar.

2020-09-03 19:30 UTC, merged