Consertando Testes e Criando Componentes
conab-devs/conab-backend pull request #39
Opened 2020-09-04 18:54 UTC by FrankKleiton

## Descrição :pencil:
> Fix de problemas de migração, refatoração de testes e funcionalidades, adição de novos testes e componentes.

**Issues :pushpin:**
> Adicione aqui as issues relacionadas com esse Pull Request
> #38 

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [x] Testes unitários ou de integração :white_check_mark:
- [x] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [x] Refatoração de código :recycle:

2020-09-04 19:30 UTC, hdev14 requested changes

2020-09-04 19:30 UTC, hdev14 commented on database/migrations/2020_09_04_165834_drop_users_table.php
> +    public function down()
faltou criar as tabelas denovo.

2020-09-04 20:14 UTC, FrankKleiton commented on database/migrations/2020_09_04_165834_drop_users_table.php
> +    public function down()
Thanks

2020-09-05 00:18 UTC, hdev14 approved these changes

2020-09-05 00:18 UTC, merged