Cooperative Admin Management
conab-devs/conab-backend pull request #60
Opened 2020-09-29 17:43 UTC by FrankKleiton

## Descrição :pencil:
> Testes e features relacionados ao gerenciamento do administrador da cooperativa, feature de autorização e seus testes. Junto a mudança do email sender para mailgun.

**Issues :pushpin:**
> fixes #3 #54 #59 

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [ ] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:
![Screenshot_2020-09-29 Captura de tela_2020-09-29_13-36-38 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/31077851/94596014-f165dc80-0261-11eb-9189-0654fe754069.png)

2020-09-29 18:34 UTC, hdev14 requested changes

2020-09-29 18:34 UTC, hdev14 commented on app/Http/Controllers/CooperativeAdminController.php
> +        });
Esse método retornar um exception?

2020-09-29 18:34 UTC, hdev14 commented on app/Http/Controllers/CooperativeAdminController.php
> +                    return response('', 400);
Faltou a mensagem de retorno.

2020-09-29 19:35 UTC, hdev14 requested changes

2020-09-29 19:35 UTC, hdev14 commented on app/Http/Requests/AdminCooperativeStore.php
> +}
Essa aqui é mesma validação que também tem no AdminConabController né. Faz a mesma coisa que eu escrevi na validação do update.

2020-09-29 19:35 UTC, hdev14 commented on tests/Feature/AdminConabControllerTest.php
> +    public function should_return_un_authorized_if_customer_try_to_list_admins()
Os testes que vc desenvolveu são feitos apenas para testar a autorização do usuário, então pode não haver a necessidade de criar factories como esse de bloco.

2020-09-29 19:35 UTC, hdev14 commented on tests/Feature/AdminCooperativeControllerTest.php
> +        $secondCooperative->admins()->save($admin);
Acho que não precisa disso, né? 🤔

2020-09-29 19:35 UTC, hdev14 commented on tests/Feature/AdminCooperativeControllerTest.php
> +    public function should_return_unauthorized_if_user_is_not_the_resource_owner_on_update()
Vi que tem alguns testes que tem um factory de phones, mas não consegui ver onde esse setup ta sendo utilizado, dá uma olhada depois.

2020-09-30 01:08 UTC, FrankKleiton commented on app/Http/Controllers/CooperativeAdminController.php
> +        });
Sim, retorna.

2020-09-30 01:21 UTC, FrankKleiton commented on tests/Feature/AdminConabControllerTest.php
> +    public function should_return_un_authorized_if_customer_try_to_list_admins()
Há, porque se não não há como saber se o usuário autenticado tem autorização a esse recurso, sem ter ele no banco, mas tem alguns testes de autorização que podem não precisar, vou dar uma olhada.

2020-09-30 16:58 UTC, hdev14 approved these changes
☕

2020-10-02 18:20 UTC, lucasemanuel approved these changes

2020-10-03 20:00 UTC, merged