Refactoring email reset
conab-devs/conab-backend pull request #80
Opened 2020-11-13 18:06 UTC by FrankKleiton

## Descrição :pencil:
> Descreva o que foi desenvolvido detalhadamente.

**Issues :pushpin:**
> Adicione aqui as issues relacionadas com esse Pull Request
> Ex.: <#numero-da-issue>

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [ ] Refatoração de código :recycle:

 ## Screenshots (opcional) :camera_flash:
 >Caso esse Pull Request seja relacionado com **frontend** é crucial ter alguma imagem para a revisão.

:poop: Não se esqueça de adicionar o Github Project, Issues, Labels e os Reviewers.

2020-11-16 11:42 UTC, lucasemanuel commented on database/migrations/2020_11_12_133358_alter_column_token_to_code.php
> +            $table->timestamps();
Por que no `down` você está recriando a tabela?

2020-11-16 12:39 UTC, hdev14 requested changes
Pq tem algumas coisas de controller de usuário aqui? 😅

2020-11-16 12:39 UTC, hdev14 commented on database/migrations/2020_11_12_133358_alter_column_token_to_code.php
> +            $table->timestamps();
Ele ta excluindo a tabela e recriando pq ele fez isso no up. Mas também não entendi pq recriar a tebela novamente. Não seria melhor só dropar a coluna e colocar a nova?

2020-11-16 12:39 UTC, hdev14 commented on resources/views/Email/resetPassword.blade.php
>  Thanks,<br>
Coloque em português a mensagem.

Também percebi que o template do email ta vindo com a formatação padrão do laravel. Seria melhor a gente colocar um do conarket.

2020-11-16 13:37 UTC, FrankKleiton commented on database/migrations/2020_11_12_133358_alter_column_token_to_code.php
> +            $table->timestamps();
É que eu sempre tenho problemas com o sqlite nos testes, então já peguei o costume de fazer o drop da tabela. Na migration de dap e profile picture eu tive uns problemas pra realizar rollback, então fiz a mal prática de alterar a migration diretamente, porque não funcionava no meu pc. Eu nem cogitei na verdade fazer o drop da coluna, é uma boa idéia, testei aqui e deu certo. Valeu.

2020-11-16 13:39 UTC, FrankKleiton commented on resources/views/Email/resetPassword.blade.php
>  Thanks,<br>
Show, vou modificar aqui.

2020-11-19 12:28 UTC, hdev14 reviewed
@FrankKleiton a queue usa o postgres mesmo ou outro banco?

2020-11-19 14:39 UTC, FrankKleiton commented
> @FrankKleiton a queue usa o postgres mesmo ou outro banco?

Postgres.

2020-11-20 00:51 UTC, hdev14 approved these changes
@FrankKleiton eu vou aprovar, mas presta atenção da próxima vez de não adicionar commits de outra branch. Tipo quando vc for fazer uma feature nova em uma nova branch, primeiro vá para a dev e crie a branch a partir dela.

2020-11-20 12:44 UTC, merged