Documentação
conab-devs/conab-backend pull request #84
Opened 2020-11-26 14:25 UTC by hdev14

## Descrição :pencil:
Instruções/configurações para execução da aplicação.

2020-11-26 14:26 UTC, hdev14 commented
Galera olhem ae e verifiquem se não está faltando nada. 👍🏾

2020-11-27 10:46 UTC, lucasemanuel requested changes
Falta os comandos para configurar o store dos arquivos no backend.

2020-11-27 13:46 UTC, FrankKleiton approved these changes
Parece bom, só fazer as alterações que Lucas requeriu e estará show.

2020-11-27 14:17 UTC, hdev14 commented
@lucasemanuel pronto dá uma olhada ae e veja se era isso que vc tava falando.

2020-11-27 14:56 UTC, lucasemanuel approved these changes

2020-11-27 14:57 UTC, merged